// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1;

namespace Project1.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210311023033_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project1.Models.Operador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("licencia")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("rut")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("id");

                    b.ToTable("Operador");
                });

            modelBuilder.Entity("Project1.Models.Tren", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("numeroTren")
                        .HasColumnType("int");

                    b.Property<string>("observacion")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("operadorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("operadorId");

                    b.ToTable("Tren");
                });

            modelBuilder.Entity("Project1.Models.Tren", b =>
                {
                    b.HasOne("Project1.Models.Operador", "operador")
                        .WithMany()
                        .HasForeignKey("operadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
